---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdintegration
  labels:
    app: cicdintegration
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cicdintegration
  template:
    metadata:
      labels:
        app: cicdintegration
    spec:
      containers:
      - name: cicdintegration
        image: sathishkatakam/devops:14
        ports:
        - containerPort: 8080

  

